const BASE_SERVER_HTTP_PROTOCOL: string = import.meta.env.VITE_BASE_SERVER_HTTP_PROTOCOL;
const BASE_SERVER_WS_PROTOCOL: string = import.meta.env.VITE_BASE_SERVER_WS_PROTOCOL;
const BASE_SERVER_URL: string = import.meta.env.VITE_BASE_SERVER_URL;

const HTTP_BASE_SERVER_URL = `${BASE_SERVER_HTTP_PROTOCOL}://${BASE_SERVER_URL}`;
const WS_BASE_SERVER_URL = `${BASE_SERVER_WS_PROTOCOL}://${BASE_SERVER_URL}`;

export {
    BASE_SERVER_HTTP_PROTOCOL,
    BASE_SERVER_WS_PROTOCOL,
    BASE_SERVER_URL,
    HTTP_BASE_SERVER_URL,
    WS_BASE_SERVER_URL
};
